name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Publish
      - name: Publish package
        run: deno publish
      