name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Publish
      - name: Publish package
        run: npx jsr publish
      